apiVersion: v1
kind: ConfigMap
metadata:
  name: hw2-config
data:
  server.port: "8000"
  spring.datasource.initialization-mode: "always"
  spring.jpa.show-sql: "true"
  spring.jpa.hibernate.ddl-auto: "none"
  spring.liquibase.change-log: "changelog.xml"
  spring.liquibase.default-schema: "public"
  spring.liquibase.enabled: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: hw2-secret
type: Opaque
data:
  spring.datasource.url: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXM6NTQzMi9UZXN0REI=
  spring.datasource.username: cG9zdGdyZXM=
  spring.datasource.password: cG9zdGdyZXM=

