replicaCount: 2

image: sbrv/hw2:v1

service:
  type: NodePort
  port: 8000

externalPostgresql:
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  postgresqlDatabase: TestDB
  postgresqlHost: "postgres"
  postgresqlPort: "5432"

server:
  port: 8000

spring:
  datasource:
    url: "jdbc:postgresql://postgres:5432/TestDB"
    username: "postgres"
    password: "postgres"
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: changelog.xml
    default-schema: "public"
    enabled: false